const fortunes = [
    "The answer you seek is closer than you think.",
    "Trust the next strange coincidence.",
    "You will soon overhear a conversation meant for you.",
    "A doorway you ignored is about to open.",
    "Someone is thinking about you right now.",
    "What you lost will return when you stop looking.",
    "Beware of advice that feels too certain.",
    "Laughter will interrupt your seriousness today.",
    "You are about to become someone’s strange story.",
    "Don’t trust the silence — it’s plotting.",
    "You will win an argument you didn’t know you were having.",
    "Something you forgot is about to remember you.",
    "There is magic in your mess.",
    "You will dream of something real.",
    "A great idea is hiding in your shower thoughts.",
    "Take the shortcut, even if it looks sketchy.",
    "A bird knows more than it lets on.",
    "An old answer will suddenly make sense.",
    "Your socks hold the key. Don’t ask why.",
    "A small mistake will lead to a fun surprise.",
    "You’re on the right path, even if it’s weird.",
    "A nap will solve at least one problem.",
    "Someone will misread your text in a hilarious way.",
    "The next snack you eat will change everything.",
    "You’re not late. Time is just early.",
    "Something odd will make you feel understood.",
    "Take the risk. Regret is louder than failure.",
    "You already know the answer. You’re just pretending you don’t.",
    "This week, the moon is on your side.",
    "Don’t knock. Just open it.",
    "You are the plot twist.",
    "A forgotten password will reveal a forgotten self.",
    "This is not the sign you're waiting for. It's the one you need.",
    "You will laugh at the wrong moment. It will be perfect.",
    "Someone will call you lucky. They’re not wrong.",
    "The best revenge is excellent snacks.",
    "An inanimate object is judging you. Gently.",
    "Chaos is your co-pilot. Buckle up.",
    "Someone will compliment you. Try to believe them.",
    "Your weirdness is trying to escape. Let it.",
    "This was meant to be strange.",
    "Everything will be fine. But first, awkward.",
    "Today is the beginning of something you won't name until later.",
    "You’ve been right more often than you admit.",
    "This isn’t the end. Just a weird middle.",
    "Look for the thing that doesn’t belong. That’s the key.",
    "You are more powerful than your to-do list implies.",
    "The universe just winked. Did you see it?",
    "Something important will arrive disguised as a distraction.",
    "Your future self is cheering for you. Loudly.",
    "If you don’t understand it now, wait until Tuesday.",
    "You will forget something on purpose today.",
    "The crystal ball is tired. Ask again after snacks.",
  ];
  
  
  window.onload = function () {
    const msg = document.getElementById("fortune");
    const random = Math.floor(Math.random() * fortunes.length);
    msg.textContent = fortunes[random];
  };
  